baseURL = "https://drox.zone/"
title = "Shell"
# author = "Yukuro"
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

[Params]

# Additions start here
  [Params.Navbar]
  use = true
  
  [Params.Extensions]
  use = true
  ext = ".txt" # extension to add after single page
# Additions stop here
    
  # Note: This is for the meta description, which is different from the "description" displayed in the terminal.
  description = "drox.zone"
  [Params.Terminal]
  # Note: color scheme
  # Note: You can choose between
  # Note: hugo-theme-shell original: ["shell-powershell", "shell-ubuntu", "shell-retro"]
  # Note: gogh theme: https://mayccoll.github.io/Gogh/
  scheme = "Gruvbox"

  # Note: in terminal
  # [userName]@[pcName]:~/$ cd [workDir]
  # [userName]@[pcName]:~/[workDir]$ cat [profile]
  #
  # [description]
  #
  # Note: if you set Params.Tree > use = true
  # [userName]@[pcName]:~/[workDir]$ tree ./[folderName]/
  # ./[folderName]/
  # ...
  # Note: result of the tree command
  userName = "user"
  pcName = "drox.zone"
  workDir = "site "
  profile = "motd.txt"

  # Note: speed at which text is displayed on the terminal
  # Note: if set to 0, typing animation will be disabled
  # Note:
  # Note: if you want to enable Mathjax, you need to set it to 0
  # Note: and set "math: true" at front matter in your Markdown file
  ps1Delay = 1 # prompt speed : [userName]@[pcName]:~/$ , [userName]@[pcName]:~/[workDir]$
  stdoutDelay = 2 # stdout speed : [description] , files in Params.Tree
  commandDelay = 40 # command speed : cd [workDir] , cat [profile] , tree ./[folderName]/

  # terminalDelay = 20 : deprecated

  # Note: speed at which text is displayed on the activity pages
  # Note: if set to 0, typing animation will be disabled
  # Note: 
  # Note: if you want to enable Mathjax, you need to set it to 0
  # Note: and set "math: true" at front matter in your Markdown file
  titleDelay = 5 # title speed : "title" in front matter
  contentDelay = 1 # content speed : content in .md file

  # activityDelay = 5 : deprecated

  description = """
  ╔══════════════════════════════════════╕
  ╟╴name: droxpopuli
  ╟╴type: embedded developer
  ╟╴things: firmware, 3D Printing,
  ║&nbsp&nbsp&nbsp&nbspgame development, synthetic sounds
  ╠══════════════════════════════════════╡
  ╟╴drox is currently working on:
  ║&nbsp&nbsp&nbsp&nbspCodename: BROADSIDE
  ╙──────────────────────────────────────┘

  """

  # Note: If you want to use a Markdown file, you can use the following
  # description = "/description.md"
  # Note: and put the description.md in /content/description.md

  [Params.Tree]
  use = true
  folderName = "activities"
  # Note: ["ACTIVITY", "URL or PATH TO YOUR MARKDOWN FILE"]
  files = [ 
    ["music -> bandcamp.com", "https://droxpopuli.bandcamp.com/"],
    ["games -> itch.io", "https://droxpopuli.itch.io/"],
    ["code&nbsp&nbsp-> github.com", "https://github.com/droxpopuli"],
    ["blog&nbsp&nbsp-> ~/posts/", "/posts/"],
  ]

[module]
  [module.hugoVersion]
    extended = true
    min = "0.85.0"
